package PokemonDB;

public enum Effect {
	
	BURN,FREEZE,PARALYZE,CONFUSE,POISON,FLINCH,
	ATTACKDROP,DEFENSEDROP,SPECIALDROP,SPEEDDROP,
	ATTACKHARSH,DEFENSEHARSH,SPECIALHARSH,SPEEDHARSH,
	ATTACKUP,DEFENSEUP,SPECIALUP,SPEEDUP,
	ATTACKSHARP,DEFENSESHARP,SPECIALSHARP,SPEEDSHARP
	

}
